module "aws_s3_bucket" {
  source = "../modules/s3-bucket"
##input variables##
enable_logging = true
bucket_name = "dev-use1-ap13-s3-testing-example"
lock_object = false
tag_Environment = "Dev"
tag_Project_Name = "ap13"
tag_Team = "devops"
tag_Owner = "eenkhchuluun@akumoproject.com"
bucket_versioning_status = "Suspended"
object_lock_mode = "GOVERNANCE"
years = "1"
block_acls = true
block_policy = true
ignore_acls = true
restrict_buckets = true
enable_life_cycle_rules = false
object_prefix = "log/"
object_tag = "dev"
current_transition_days = 60
current_transition_storage_class = "STANDARD_IA"
current_expiration_days = 360
non_current_transition_days = 30
non_current_transition_storage_class = "STANDARD_IA"
non_current_expiration_days = 360
enable_encryption = false
sse_algorithm = "aws:kms"
kms_key_arn = ""
transfer_acceleration = "Enabled"
website_enable = true
key_prefix_equals = "docs/"
replace_key_prefix_with = "documents/"
}
